# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f <- function(x) {
    .Call('_StatComp20028_f', PACKAGE = 'StatComp20028', x)
}

rwMetropolis <- function(sigma, x0, N) {
    .Call('_StatComp20028_rwMetropolis', PACKAGE = 'StatComp20028', sigma, x0, N)
}

